version: '3.8'

services:
  app:
    build: .
    container_name: auth_services
    ports: [3001:3001]
    environment:
      - PORT=3001
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DYNAMODB_ENDPOINT=
      - DYNAMODB_TABLE_NAME=Users
      - JWT_SECRET=secret
    volumes:
      - ./:/app
  