FROM docker.io/library/golang AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go install github.com/air-verse/air@latest
RUN go install github.com/gin-gonic/gin
RUN go mod download

COPY . . 

RUN go mod tidy && CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app/main ./cmd/api 

FROM debian:bullseye-slim

WORKDIR /app

COPY --from=builder /app/main .

EXPOSE 3001

#ENTRYPOINT [ "air", "-c", ".air.toml" ]
CMD [ "sh", "-c", "./main"]